project:
  type: website

website:
  title: "Robotics Handbook"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "SLAM"
        contents:
          - section: "Factor Graphs for SLAM"
            contents:
              - chapters/factor-graphs-slam/overview.qmd
              - chapters/factor-graphs-slam/Visualizing_SLAM_with_factor_graphs.qmd
              - chapters/factor-graphs-slam/least_squares.qmd
              - chapters/factor-graphs-slam/linearization.qmd
              - chapters/factor-graphs-slam/cholesky_qr.qmd
              - chapters/factor-graphs-slam/gradient_newton.qmd
              - chapters/factor-graphs-slam/sparsity.qmd
              - chapters/factor-graphs-slam/variable_ordering.qmd
          - section: "Handwritten Notes"
            contents:
              - chapters/factor-graphs-slam/handwritten-notes/factor-graphs-slam.qmd

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
    number-sections: true
    html-math-method: mathjax