project:
  type: website

website:
  title: "Robotics Handbook"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "SLAM"
        contents:
          - section: "Factor Graphs for SLAM"
            contents:
              - chapters/factor-graphs-slam/overview.qmd
              - chapters/factor-graphs-slam/Visualizing_SLAM_with_factor_graphs.qmd
              - chapters/factor-graphs-slam/least_squares.qmd

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
    html-math-method: mathjax